/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionalmacen.Vistas;


import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;


public class IniciarSesion extends javax.swing.JFrame {
 
    public IniciarSesion() {
        initComponents();
        setVisible(true);//Hace visible la ventana, porque por default no lo hace
    }
    
    //Funcion iniciar sesion
    public void iniciarSesion(){
        String user = CampoUsuario.getText();//Mediante el getText() extraemos lo que está en el CampoUsuario
        String password = CampoContraseña.getText();//En este caso es algo distinto. Aparece rayado porque es una funcion desactualizada pero sirve aún
        
        //OlvaCourier.usuarioActual = OlvaCourier.personas.validar(user, password);

        /*if(OlvaCourier.usuarioActual != null){
            JOptionPane.showMessageDialog(null, "Bienvenido");
            int tUsuario = OlvaCourier.usuarioActual.getTipoFuncion(); //La funcion como se estableció tUsuario 1=cliente 2=administrador
            
            switch (tUsuario) {
                case 1:
                    
                    //Cliente
                    //OlvaCourier.clienteActual = (Cliente) OlvaCourier.personas.getPersona(OlvaCourier.usuarioActual); //Convierte la persona conseguida en el cliente actual
                    //FrmCliente form = new FrmCliente(); //Ingresamos al formulario del cliente
                    //this.dispose();
                    break;
                    
                case 2:
                    //Administrador
                    
                    //OlvaCourier.administradorActual = (Administrador) OlvaCourier.personas.getPersona(OlvaCourier.usuarioActual);
                    //FrmAdministrador fa = new FrmAdministrador();
                    //this.dispose();
                    
                    break;
            }

        }else{//datos erroneos
            JOptionPane.showMessageDialog(null,"ERROR");//No se encontro el usuario y/o contraseña introducida

            this.CampoUsuario.setText("");
            this.CampoContraseña.setText("");
        }*/
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Fondo = new javax.swing.JPanel();
        IngresoDatos = new javax.swing.JPanel();
        CampoUsuario = new javax.swing.JTextField();
        etiquetaUsuario = new javax.swing.JLabel();
        etiquetaContraseña = new javax.swing.JLabel();
        CampoContraseña = new javax.swing.JPasswordField();
        botonIngresar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        FondoMarca = new javax.swing.JPanel();
        FondoHead = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FondoImagen = new javax.swing.JPanel();
        Imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        IngresoDatos.setBackground(new java.awt.Color(255, 211, 105));
        IngresoDatos.setForeground(new java.awt.Color(255, 255, 255));

        CampoUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CampoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoUsuarioActionPerformed(evt);
            }
        });
        CampoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CampoUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoUsuarioKeyTyped(evt);
            }
        });

        etiquetaUsuario.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        etiquetaUsuario.setForeground(new java.awt.Color(56, 56, 55));
        etiquetaUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaUsuario.setText("Usuario");

        etiquetaContraseña.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        etiquetaContraseña.setForeground(new java.awt.Color(56, 56, 55));
        etiquetaContraseña.setText("Contraseña");

        CampoContraseña.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CampoContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoContraseñaActionPerformed(evt);
            }
        });
        CampoContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CampoContraseñaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CampoContraseñaKeyTyped(evt);
            }
        });

        botonIngresar.setBackground(new java.awt.Color(64, 170, 173));
        botonIngresar.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        botonIngresar.setForeground(new java.awt.Color(56, 56, 55));
        botonIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionalmacen/Vistas/iconos/IniciarSesion.png"))); // NOI18N
        botonIngresar.setBorderPainted(false);
        botonIngresar.setContentAreaFilled(false);
        botonIngresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionalmacen/Vistas/iconos/IniciarSesionPresionado.png"))); // NOI18N
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });

        botonSalir.setBackground(new java.awt.Color(64, 170, 173));
        botonSalir.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(56, 56, 55));
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionalmacen/Vistas/iconos/Salir.png"))); // NOI18N
        botonSalir.setBorderPainted(false);
        botonSalir.setContentAreaFilled(false);
        botonSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionalmacen/Vistas/iconos/SalirPresionado.png"))); // NOI18N
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IngresoDatosLayout = new javax.swing.GroupLayout(IngresoDatos);
        IngresoDatos.setLayout(IngresoDatosLayout);
        IngresoDatosLayout.setHorizontalGroup(
            IngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngresoDatosLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(botonIngresar)
                .addGap(23, 23, 23)
                .addComponent(botonSalir)
                .addGap(272, 272, 272))
            .addGroup(IngresoDatosLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(IngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CampoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaContraseña)
                    .addComponent(etiquetaUsuario)
                    .addComponent(CampoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        IngresoDatosLayout.setVerticalGroup(
            IngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngresoDatosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(etiquetaUsuario)
                .addGap(18, 18, 18)
                .addComponent(CampoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(etiquetaContraseña)
                .addGap(26, 26, 26)
                .addComponent(CampoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(IngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonIngresar)
                    .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        FondoMarca.setBackground(new java.awt.Color(138, 196, 208));
        FondoMarca.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        FondoHead.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        FondoHead.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FondoHead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionalmacen/Vistas/iconos/FISI.jpg"))); // NOI18N
        FondoHead.setLabelFor(FondoHead);
        FondoHead.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        FondoHead.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        FondoHead.setMaximumSize(new java.awt.Dimension(300, 300));
        FondoHead.setMinimumSize(new java.awt.Dimension(219, 82));
        FondoHead.setPreferredSize(new java.awt.Dimension(230, 93));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(87, 86, 86));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("FISI(A Modificar)");
        jLabel2.setToolTipText("");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout FondoMarcaLayout = new javax.swing.GroupLayout(FondoMarca);
        FondoMarca.setLayout(FondoMarcaLayout);
        FondoMarcaLayout.setHorizontalGroup(
            FondoMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoMarcaLayout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(FondoHead, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(FondoMarcaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(203, 203, 203))
        );
        FondoMarcaLayout.setVerticalGroup(
            FondoMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoMarcaLayout.createSequentialGroup()
                .addComponent(FondoHead, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionalmacen/Vistas/iconos/FondoFisi.jpg"))); // NOI18N

        javax.swing.GroupLayout FondoImagenLayout = new javax.swing.GroupLayout(FondoImagen);
        FondoImagen.setLayout(FondoImagenLayout);
        FondoImagenLayout.setHorizontalGroup(
            FondoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoImagenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        FondoImagenLayout.setVerticalGroup(
            FondoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoImagenLayout.createSequentialGroup()
                .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FondoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FondoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(IngresoDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(FondoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FondoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IngresoDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 922, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CampoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoUsuarioActionPerformed

    private void CampoContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoContraseñaActionPerformed
        
    }//GEN-LAST:event_CampoContraseñaActionPerformed
    
    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        
        GestorArticulos form = new GestorArticulos();
        this.dispose();

        

        
        
        
        
        
        
        

        /*//OlvaCourier.CargarListas(l);
        //l.desplegarLista();
        
        iniciarSesion();
        */
    }//GEN-LAST:event_botonIngresarActionPerformed

    private void CampoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoUsuarioKeyTyped

    }//GEN-LAST:event_CampoUsuarioKeyTyped

    private void CampoContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoContraseñaKeyTyped
        
    }//GEN-LAST:event_CampoContraseñaKeyTyped

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped

    }//GEN-LAST:event_formKeyTyped

    private void CampoUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoUsuarioKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            iniciarSesion();
        }
        
        /*if(CampoUsuario.getText().length()<8){
            CampoUsuario.setBackground(Color.red);
        }else{
            CampoUsuario.setBackground(Color.WHITE);
        }*/
    }//GEN-LAST:event_CampoUsuarioKeyPressed

    private void CampoContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoContraseñaKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            iniciarSesion();
        }
    }//GEN-LAST:event_CampoContraseñaKeyPressed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });
        
        //Colocarlo en el main principal 
        /*Conexion.Conexion.getConexion();*/
     
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CampoContraseña;
    private javax.swing.JTextField CampoUsuario;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel FondoHead;
    private javax.swing.JPanel FondoImagen;
    private javax.swing.JPanel FondoMarca;
    private javax.swing.JLabel Imagen;
    private javax.swing.JPanel IngresoDatos;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel etiquetaContraseña;
    private javax.swing.JLabel etiquetaUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
