/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionalmacen.Vistas;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

public class IniciarSesion extends javax.swing.JFrame {

    public IniciarSesion() {
        initComponents();
        setVisible(true);//Hace visible la ventana, porque por default no lo hace
    }

    //Funcion iniciar sesion
    public void iniciarSesion() {

        // String user = CampoUsuario.getText();
////Mediante el getText() extraemos lo que está en el CampoUsuario
//        String password = user.getText();//En este caso es algo distinto. Aparece rayado porque es una funcion desactualizada pero sirve aún
        //OlvaCourier.usuarioActual = OlvaCourier.personas.validar(user, password);

        /*if(OlvaCourier.usuarioActual != null){
            JOptionPane.showMessageDialog(null, "Bienvenido");
            int tUsuario = OlvaCourier.usuarioActual.getTipoFuncion(); //La funcion como se estableció tUsuario 1=cliente 2=administrador
            
            switch (tUsuario) {
                case 1:
                    
                    //Cliente
                    //OlvaCourier.clienteActual = (Cliente) OlvaCourier.personas.getPersona(OlvaCourier.usuarioActual); //Convierte la persona conseguida en el cliente actual
                    //FrmCliente form = new FrmCliente(); //Ingresamos al formulario del cliente
                    //this.dispose();
                    break;
                    
                case 2:
                    //Administrador
                    
                    //OlvaCourier.administradorActual = (Administrador) OlvaCourier.personas.getPersona(OlvaCourier.usuarioActual);
                    //FrmAdministrador fa = new FrmAdministrador();
                    //this.dispose();
                    
                    break;
            }

        }else{//datos erroneos
            JOptionPane.showMessageDialog(null,"ERROR");//No se encontro el usuario y/o contraseña introducida

            this.CampoUsuario.setText("");
            this.CampoContraseña.setText("");
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Fondo = new javax.swing.JPanel();
        IngresoDatos = new javax.swing.JPanel();
        etiquetaUsuario = new javax.swing.JLabel();
        etiquetaContraseña = new javax.swing.JLabel();
        botonIngresar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        Text_Password = new javax.swing.JPasswordField();
        Text_user = new javax.swing.JTextField();
        FondoMarca = new javax.swing.JPanel();
        FondoHead = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FondoImagen = new javax.swing.JPanel();
        Imagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        Fondo.setBackground(new java.awt.Color(18, 48, 87));

        IngresoDatos.setBackground(new java.awt.Color(226, 162, 43));
        IngresoDatos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(18, 48, 87), 10, true));
        IngresoDatos.setForeground(new java.awt.Color(255, 255, 255));

        etiquetaUsuario.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        etiquetaUsuario.setForeground(new java.awt.Color(56, 56, 55));
        etiquetaUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaUsuario.setText("Usuario");

        etiquetaContraseña.setFont(new java.awt.Font("Yu Gothic UI", 1, 16)); // NOI18N
        etiquetaContraseña.setForeground(new java.awt.Color(56, 56, 55));
        etiquetaContraseña.setText("Contraseña");

        botonIngresar.setBackground(new java.awt.Color(64, 170, 173));
        botonIngresar.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        botonIngresar.setForeground(new java.awt.Color(56, 56, 55));
        botonIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionalmacen/Vistas/iconos/IniciarSesion.png"))); // NOI18N
        botonIngresar.setText("Ingresar");
        botonIngresar.setBorderPainted(false);
        botonIngresar.setContentAreaFilled(false);
        botonIngresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonIngresar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionalmacen/Vistas/iconos/IniciarSesionPresionado.png"))); // NOI18N
        botonIngresar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });

        botonSalir.setBackground(new java.awt.Color(64, 170, 173));
        botonSalir.setFont(new java.awt.Font("Yu Gothic UI", 3, 14)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(56, 56, 55));
        botonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionalmacen/Vistas/iconos/Salir.png"))); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.setBorderPainted(false);
        botonSalir.setContentAreaFilled(false);
        botonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionalmacen/Vistas/iconos/SalirPresionado.png"))); // NOI18N
        botonSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        Text_Password.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Text_Password.setForeground(new java.awt.Color(51, 153, 255));
        Text_Password.setEchoChar('\u25cf');
        Text_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_PasswordActionPerformed(evt);
            }
        });

        Text_user.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Text_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_userActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IngresoDatosLayout = new javax.swing.GroupLayout(IngresoDatos);
        IngresoDatos.setLayout(IngresoDatosLayout);
        IngresoDatosLayout.setHorizontalGroup(
            IngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngresoDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaContraseña)
                    .addComponent(etiquetaUsuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IngresoDatosLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(IngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Text_user, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(IngresoDatosLayout.createSequentialGroup()
                        .addComponent(botonIngresar)
                        .addGap(18, 18, 18)
                        .addComponent(botonSalir))
                    .addComponent(Text_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        IngresoDatosLayout.setVerticalGroup(
            IngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngresoDatosLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(etiquetaUsuario)
                .addGap(18, 18, 18)
                .addComponent(Text_user, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(etiquetaContraseña)
                .addGap(18, 18, 18)
                .addComponent(Text_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addGroup(IngresoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IngresoDatosLayout.createSequentialGroup()
                        .addComponent(botonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(255, 255, 255))
                    .addGroup(IngresoDatosLayout.createSequentialGroup()
                        .addComponent(botonIngresar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        FondoMarca.setBackground(new java.awt.Color(255, 255, 255));
        FondoMarca.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        FondoHead.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        FondoHead.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        FondoHead.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionalmacen/Vistas/iconos/FISI.jpg"))); // NOI18N
        FondoHead.setLabelFor(FondoHead);
        FondoHead.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        FondoHead.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        FondoHead.setMaximumSize(new java.awt.Dimension(300, 300));
        FondoHead.setMinimumSize(new java.awt.Dimension(219, 82));
        FondoHead.setPreferredSize(new java.awt.Dimension(230, 93));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sistema de Almacén de FISI");
        jLabel2.setToolTipText("");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout FondoMarcaLayout = new javax.swing.GroupLayout(FondoMarca);
        FondoMarca.setLayout(FondoMarcaLayout);
        FondoMarcaLayout.setHorizontalGroup(
            FondoMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoMarcaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(FondoHead, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(740, Short.MAX_VALUE))
        );
        FondoMarcaLayout.setVerticalGroup(
            FondoMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoMarcaLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(FondoMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FondoHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        FondoImagen.setBackground(new java.awt.Color(18, 48, 87));

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionalmacen/Vistas/iconos/FondoFisi.jpg"))); // NOI18N

        javax.swing.GroupLayout FondoImagenLayout = new javax.swing.GroupLayout(FondoImagen);
        FondoImagen.setLayout(FondoImagenLayout);
        FondoImagenLayout.setHorizontalGroup(
            FondoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoImagenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FondoImagenLayout.setVerticalGroup(
            FondoImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoImagenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FondoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(FondoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(IngresoDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(FondoMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FondoImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IngresoDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        String usuario = Text_user.getText();
        String contraseña = Text_Password.getText();

        if (usuario.isEmpty() || contraseña.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Algún campo está vacio");
        } else {
            if (usuario.equals("almacenista") && contraseña.equals("1234")) {
                JOptionPane.showMessageDialog(null, "Bienvenido !!   Almacenista");
                GestorArticulos form = new GestorArticulos();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Su usuario o contraseña son incorrectos");
            }

        }


    }//GEN-LAST:event_botonIngresarActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped

    }//GEN-LAST:event_formKeyTyped

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void Text_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_PasswordActionPerformed

    private void Text_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IniciarSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IniciarSesion().setVisible(true);
            }
        });

        //Colocarlo en el main principal 
        /*Conexion.Conexion.getConexion();*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel FondoHead;
    private javax.swing.JPanel FondoImagen;
    private javax.swing.JPanel FondoMarca;
    private javax.swing.JLabel Imagen;
    private javax.swing.JPanel IngresoDatos;
    private javax.swing.JPasswordField Text_Password;
    private javax.swing.JTextField Text_user;
    private javax.swing.JButton botonIngresar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel etiquetaContraseña;
    private javax.swing.JLabel etiquetaUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
